run-name: Spotify Anoymous Token Extractor
on: [push]
jobs:
    main:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses : actions/setup-python@v2
              with:
                python-version: '3.11'

            - name : Install UV 
              run: pip install uv   
            
            - name : Setup Chrome 
              uses: browser-actions/setup-chrome@v1
              with:
                chrome-version: 120
                install-dependencies: true  
            
            - name: Run Extractor
              run : uv run main.py  
            
          
    