run-name: Spotify Anoymous Token Extractor
on: [push]
jobs:
    main:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses : actions/setup-python@v2
              with:
                python-version: '3.11'

            - name : Install UV 
              run: pip install uv   
            
            - name: Install Chrome
              run: |
                sudo apt update
                sudo apt install -y wget gnupg unzip
                wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > google.gpg
                sudo install -o root -g root -m 644 google.gpg /usr/share/keyrings/
                echo "deb [signed-by=/usr/share/keyrings/google.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
                sudo apt update
                sudo apt install -y google-chrome-stable
                google-chrome-stable --version 
            
            - name: Run Extractor
              run : uv run main.py  
            
          
    